config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_eww:
    src: config/eww
    dst: ~/.config/eww
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
profiles:
  manjaro:
    dotfiles:
    - d_eww
    - d_nvim
    - d_alacritty
