config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_wired:
    src: config/wired
    dst: ~/.config/wired
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_xplr:
    src: config/xplr
    dst: ~/.config/xplr
  d_eww:
    src: config/eww
    dst: ~/.config/eww
profiles:
  artix:
    dotfiles:
    - d_alacritty
    - d_wired
    - d_nvim
    - d_xplr
    - d_eww
